### ISSUE TITLE
Text is invisible while minimizing and maximizing the shell

### ISSUE THREAD

**Issue by isubham** [codebytere/codebytere.github.io#30] opened 2020-05-08 03:49 UTC

**Comment by 250683** [comment] 2020-10-07 20:17
Duplicate of #

**Comment by 250683** [comment] 2020-10-07 22:18
> _Ingen beskrivelse gitt._

@g1eb

**Comment by codebytere** [comment] 2020-10-08 00:10
Closing as i cannot repro this anymore.

**Closed as completed by codebytere** 2020-10-08 00:10 UTC
